#!/usr/bin/env python

"""Quick and basic test runner

Runs scrub script with data from each sub-directory in `./tests` directory,
then compares actual output with expected. Uses a "fast-fail" approach, quitting
as soon as a test failure has occurred.

NOTE: This will create and then remove an `output.json` file in the current
working directory. Use with caution if there is a pre-existing `output.json`
file that should not be overwritten or removed.

"""

import os
import subprocess
import json


def main():
    dirs = sorted([dir[0] for dir in os.walk("./tests")][1:])
    for dir in dirs:
        print(f"Running test in {dir}")
        subprocess.run(
            f"./scrub {dir}/sensitive_fields.txt {dir}/input.json", shell=True
        )
        with open("output.json") as f:
            actual = json.load(f)
        with open(f"{dir}/output.json") as f:
            expected = json.load(f)

        if actual != expected:
            print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(f"{dir} test failed:")
            with open(f"{dir}/sensitive_fields.txt") as f:
                sensitive_fields = f.read().splitlines()
                print(f"sensitive_fields: {sensitive_fields}")
            print(f"A: {actual}")
            print(f"E: {expected}")
            os.remove("output.json")
            quit()
        else:
            print(f"{dir} test passed................\n")

    # Clean up
    os.remove("output.json")


if __name__ == "__main__":
    main()
